server:
  port: 9999
spring:
  application:
    name: fishnet
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    fishnet:
      path: /fishnet/**
      service-id: whale
    route:
      path: /route/163
      url: http://www.163.com/
    route163:
      url: http://www.163.com/
    testforward:
      path: /testforward/**
      url: forward:/own/to
  ignored-patterns: /own/**
      
